config/routes.rb
Rails.application.routes.draw do
  get 'test/index'
  get 'welcome/index'
  root "welcome#index"

  resources :questions
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :questions
  validates :category, presence: true

end

app/models/question.rb
class Question < ApplicationRecord

  validates :question, presence: true
  validates :choice1, presence: true
  validates :choice2, presence: true
  validates :choice3, presence: true
  validates :choice4, presence: true
  validates :explanation, presence: true
  validates :answer, inclusion: 1..4

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :choice1, :choice2, :choice3, :choice4, :answer, :report, :explanation)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  RANDOM_LIMIT = 10

  def index
    @totalcategories = Category.count
    @totalquestions = Question.count
    @questions = Question.limit(RANDOM_LIMIT).order("RANDOM()")
    #@questions = Question.all



    if Question.count < 1

      @msg = 'not enough questions in the database...'
    else
      @msg = 'Choosing 10 random questions...'



    end

  end

  def show
    @question = Question.random
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %><br/>
<%= link_to "Back" , welcome_index_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onlinequiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">

    <%= form.label :category_id %><br/>

    <%= form.collection_select :category_id, Category.all, :id, :category %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_area :question %>
  </div>

  <div class="field">
    <%= form.label "Multiple choice 1" %>
    <%= form.text_area :choice1 %>
  </div>

  <div class="field">
    <%= form.label "Multiple choice 2" %>
    <%= form.text_area :choice2 %>
  </div>

  <div class="field">
    <%= form.label "Multiple choice 3" %>
    <%= form.text_area :choice3 %>
  </div>

  <div class="field">
    <%= form.label "Multiple choice 4" %>
    <%= form.text_area :choice4 %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.number_field(:answer, in: 1..4, step: 1) %>
    <%#= form.number_field :answer %>
  </div>

  <div class="field">
    <%= form.label :explanation %>
    <%= form.text_area :explanation %>
  </div>

  <div class="field">
    <%= form.label :report %>
    <%= form.check_box :report %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
acc[i].addEventListener("click", function() {
/* Toggle between adding and removing the "active" class,
to highlight the button that controls the panel */
this.classList.toggle("active");

/* Toggle between hiding and showing the active panel */
var panel = this.nextElementSibling;
if (panel.style.display === "block") {
panel.style.display = "none";
} else {
panel.style.display = "block";
}
});
}
</script>

<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Choice1</th>
      <th>Choice2</th>
      <th>Choice3</th>
      <th>Choice4</th>
      <th>Answer</th>
      <th>Explanation</th>
      <th>Report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= question.choice1 %></td>x`
        <td><%= question.choice2 %></td>
        <td><%= question.choice3 %></td>
        <td><%= question.choice4 %></td>
        <td><%= question.answer %></td>
        <td><%= question.explanation %></td>

        <td><%= question.report %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %><br/>
<%= link_to "Back" , welcome_index_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Choice1:</strong>
  <%= @question.choice1 %>
</p>

<p>
  <strong>Choice2:</strong>
  <%= @question.choice2 %>
</p>

<p>
  <strong>Choice3:</strong>
  <%= @question.choice3 %>
</p>

<p>
  <strong>Choice4:</strong>
  <%= @question.choice4 %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Report:</strong>
  <%= @question.report %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/welcome/index.html.erb
<h1>Welcome to JG's online quiz</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Categories" , categories_path %><br/>
<%= link_to "Questions" , questions_path %><br/>
<%= link_to "Test your knowledge" , test_index_path %>